version: '3.8'

services:
  poor-backend:
    build: ./poorbook-backend
    image: poor-backend:1.0
    container_name: poor-backend
    environment:
      - MONGO_HOST=poor-database
      - MONGO_DATABASE=poor_db
      - ALLOWED_HOSTS=*
      - ALLOW_METHODS=GET,POST,PUT,DELETE
      - ALLOW_HEADERS=*
      - API_KEY=ioxnsaunxa
    networks:
      - poor-network
    ports:
      - "8000:8000"
    depends_on:
      - poor-database
    restart: always

  poor-database:
    image: mongo:latest
    container_name: poor-db
    networks:
      - poor-network
    volumes:
      - poor_data:/data/db
    restart: always

  frontend:
    build:
      context: ./poorbook-front
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Map port 80 inside container to 3000 outside
    volumes:
      - ./poorbook-front:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL=http://poor-backend:8000/api/v1
    networks:
      - poor-network

networks:
  poor-network:
    driver: bridge

volumes:
  poor_data:
    driver: local
